apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::767397679511:role/eksctl-expense-nodegroup-node-NodeInstanceRole-xR10PbU7uqtz
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-admin
      userarn: arn:aws:iam::767397679511:user/k8-admin
      username: k8-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-28T04:14:17Z"
  name: aws-auth
  namespace: kube-system
  uid: 080e11b5-4929-4a9a-bb67-da5a11b1203a

